# Generated by Django 3.0.2 on 2020-05-08 03:42

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', mdeditor.fields.MDTextField()),
                ('article_type', models.IntegerField(choices=[(0, '机器学习'), (1, '深度学习')])),
                ('recommend', models.BooleanField(choices=[(True, '是'), (False, '否')], db_column='是否推荐', default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('content_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unreal.Article')),
            ],
            options={
                'ordering': ['-content_id', 'id'],
            },
        ),
    ]
