# Generated by Django 3.0.2 on 2020-05-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unreal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('content_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unreal.Comment')),
            ],
            options={
                'ordering': ['-content_id', 'id'],
            },
        ),
    ]
